name: Build LuceeDebug Agent

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        cache: 'npm'
        cache-dependency-path: vscode-client/package-lock.json
    - name: Install vsce
      run: npm i -g @vscode/vsce
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Setup Gradle and Build LuceeDebug Java Agent
      uses: gradle/gradle-build-action@v2
      with:
        arguments: shadowjar
    - name: Build LuceeDebug VS Code Extension
      run: |
        cd vscode-client
        npm install
        npm run build-dev-linux
        vsce package
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: luceedebug
        path: |
          luceedebug/vscode-client/*.vsix
          luceedebug/build/libs/*.jar
